### ISSUE TITLE
Commands stop working after using /reload

### ISSUE THREAD

**Issue by TiagoDanin** [Maciej916/Ma-Essentials#56] opened 2020-06-29 19:28 UTC
**Describe the bug**
Commands stop working after using /reload
![image](https://user-images.githubusercontent.com/5731176/86046889-625be500-ba24-11ea-9369-2b1ed3dc043c.png)

**To Reproduce**
1. Install Forge Server version in your server
1. Open your Minecraft with Forge Client Version
1. Join in your Minecraft Server
1. Run the command `/kits` this working
1. Run the command `/reload`
1. Run again the command `/kits`
1. See error

**Expected behavior**
Commands worked after reloading

**Versions**
- **Minicraft Version**: 1.16.1 with Forge
- **Ma Essentials**: [3.2.1](https://www.curseforge.com/minecraft/mc-mods/maessentials/files/2990160)
- **Forge**: [32.0.25](https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.1-32.0.25/forge-1.16.1-32.0.25-installer.jar)
- **Java** (Server):
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```
- **Java** (Client):
```
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
```

**Additional context**
Without

**Comment by Maciej916** [comment] 2020-06-30 10:15
Thank you for reporting the issue, I'll investigate that.

**Comment by bessiq** [comment] 2020-07-04 22:51
I can confirm this is happening for me also. Ma Essentials 3.2.1 on Forge 32.0.47. I stumbled across the issue in a different way, though. I had just installed several new mods, and noticed I couldn't do /day or any other Ma commands. So, I went and disabled the new mods one by one. Disabling Blue Power made the Ma commands work again, so I did a /reload as a test, which then broke the commands again. My guess is Blue Power must also be doing its own reload at some point? idk, but thought I'd share in case the info is helpful.

Thanks for making such useful and easy commands!

**Comment by bessiq** [comment] 2020-07-09 23:17
Just wanted to add that a /reload seems to break all non-vanilla commands currently. I'm on Forge 32.0.61 now, and have tested with the TellMe and Server Utilities mods and they all stop working after a reload. So, it could be a Forge and/or 1.16 issue?

**Comment by Maciej916** [comment] 2020-07-10 08:35
I think it's forge issue, we will see if it still persist in stable release.

**Comment by Maciej916** [comment] 2020-08-03 19:32
It should be fixed now with newer forge.

**Comment by Maciej916** [comment] 2020-08-03 19:34
I'll consider to make it as a separate mod because it shouldn't be hard to make.

**Closed as completed** 2020-08-03 19:34 UTC
Labels: bug
