### ISSUE TITLE
Invsee GUI immediately closes

### ISSUE THREAD

**Issue by LezChap** [Maciej916/Ma-Essentials#28] opened 2019-12-31 20:29 UTC
**Describe the bug**
Trying to use the /invsee on a server.  I see a gray GUI screen flash open for a split second most of the time, and then immediately close before I can make out any details.  No errors or anything else show up in the console logs (both server and client logs).

**Versions**
- **Ma Essentials**: 1.2.9
- **Forge**: 28.1.109

**Comment by Maciej916** [comment] 2020-01-07 19:08
I'll check that

**Comment by ApexTheElite** [comment] 2020-02-11 03:43
This is still happening on 1.15.2

Forge version: 1.15.2-31.1.1
Ma-Essentials Version: 3.0.0

**Comment by winnieduhpoooh** [comment] 2020-04-30 08:08
I figured out today you can only /invsee in front of the player. It's not a bug.

**Comment by AngelicBeatz** [comment] 2020-05-22 12:58
so it is like an checking a chest if you are to far you can't see it ok.

**Comment by Maciej916** [comment] 2020-06-05 10:24
It's a bug and it will be fixed in future update, because it should work always not only if you are close enough to player.

**Closed by Maciej916** 2020-06-05 10:24 UTC
Labels: bug
