### ISSUE TITLE
[1.15.2] /home doesnt work, /home home does

### ISSUE THREAD

**Issue by Salamance73** [Maciej916/Ma-Essentials#53] opened 2020-06-12 03:34 UTC
**Describe the bug**
As stated in the title, the previous version of the mod (v3.0.3) allowed the player to use "/home" to go to the home named "home" without having to type the second "home" out. In v3.1.0 this feature is bugged and forces the player to type "home" twice to get to the home at all. 

**To Reproduce**
1. Open chat and set a home as "/sethome home"
2. Open chat and use /home, expecting to go home
3. See syntax error listed.

**Expected behavior**
/home should teleport the player to the home named "home" without typing it again.

**Versions**
- **Ma Essentials**: 3.1.0
- **Forge**: 31.2.9

**Additional context**
This is occurring in AllTheMods5 modpack if that makes any difference.
![image](https://user-images.githubusercontent.com/26430914/84461954-58b83c00-ac33-11ea-9df9-0f7c61e8e0e3.png)

**Comment by Maciej916** [comment] 2020-06-13 17:29
I think answer on your issue is here https://github.com/Maciej916/Ma-Essentials/issues/54 there is a bug with wrong catalog name and your homes probably are not reading correctly, let me know if this fix your issue if not i'll investigate further because I tested it and it worked just fine for me.

**Comment by GatekeeperTDS** [comment] 2020-06-13 17:36
Hi - I run a server with Salamance73. I don't think this has anything to do with the folder name change in linked issue #53. When I updated our ATM server, I did have to change the folder name from ma-essentials to maessentials, which brought over all of our data.

The issue is that "/home" doesn't take you to the default home, instead "/home home" is required. I've even deleted the home named "home," recreated it, and the same thing happens.

The catalog names are fine and the homes are reading correctly.

Thank you.

**Comment by Maciej916** [comment] 2020-06-13 18:12
I found the issue, I was trying to make that if user have only one home /home will always teleport to that home no matter the name and i think the issue is with that part. I'll will just revert old functionality and it should fix the issue.

**Comment by GatekeeperTDS** [comment] 2020-06-14 16:29
Installed the latest update and this works great. Thank you for taking care of this! :)

**Comment by Maciej916** [comment] 2020-06-15 09:17
Fixed in [v3.1.1](https://www.curseforge.com/minecraft/mc-mods/maessentials/files/2979463)

**Closed as completed by Maciej916** 2020-06-15 09:17 UTC
Labels: bug
